### ISSUE TITLE
Not highlighting Types

### ISSUE THREAD

**Issue by serkonda7** [serkonda7/vscode-vba#10]
e.g. Int, String, Boolean, Object, ...

**Comment by bopoh13** [comment]
Could you find time to discuss the basics of VBA language so that we don't have disagreement?

In the group `type` declared highlight values are now:
https://github.com/serkonda7/vscode-vba/blob/9dd72ff03449caa9b8f1f8e6797689378d597fad/syntaxes/vba.tmLanguage.json#L76-L79

The official help says that [VBA has only 12 types](https://docs.microsoft.com/en-us/office/vba/language/concepts/getting-started/using-data-types-efficiently). I correctly understand what is required to replace 78 string on:
``` json
"match": "\\b(B(yte|oolean)|Integer|Long|Object|S(ingle|tring)|Currency|D(ate|ouble|ecimal)|Variant)\\b"
```

**Comment by serkonda7** [comment]
First off: the list of types currently specified for highlighting is not complete or verified. I appreciate discussing this :)

On another [page of the docs](https://docs.microsoft.com/en-us/office/vba/language/reference/user-interface-help/data-type-summary) some more additional types to the 12 are mentioned: Collection, Dictionary, LongLong, LongPtr
So line 78 has to be at least (sorted somewhat alphabetically)
```json
"match": "\\b(B(yte|oolean)|C(urrency|ollection)|D(ate|ouble|ecimal|ictionary)|Integer|Long(Long|Ptr)?|Object|S(ingle|tring)|Variant)\\b"
```

If I remember correctly, the other types currently highlighted were somewhat hidden in the docs.

**Comment by serkonda7** [comment]
Here is the source, I got the current list from: https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/data-types/
It's the reference for .NET Visual Basic, which I missed back then.

We may check if these types are valid in VBA too.

**Comment by bopoh13** [comment]
I am glad that we discussed basics issue at an early stage. Nonetheless .NET Visual Basic has syntax very different from VBA syntax.

I agree, the list of types at the moment is not complete. I sorted values in ascending order of their memory :) While there was a mention that type [`Decimal` can no longer declare](https://docs.microsoft.com/en-us/office/vba/Language/Concepts/Getting-Started/deftype-statements) (checked in version 7.1.1048):

- `Dim num As Decimal`: _Compile error. Expected: New or type name_
- `DefDec A-Z`: _Compile error. Expected: line number or label or statement or end of statement_

Another question: VB/VBA is a case-insensitive language with automatic case alignment for most of object model. Maybe make code highlighting case insensitive?

**Comment by bopoh13** [comment]
- `Dim chr As Char` ': _Compile error. User-defined type not defined_
- `Dim dic As Dictionary` ': _Compile error. User-defined type not defined_
- `Dim sbt As SByte` ': _Compile error. User-defined type not defined_
- `Dim sht As Short` ': _Compile error. User-defined type not defined_
- `Dim uit As UInteger` ': _Compile error. User-defined type not defined_
- `Dim ulg As ULong` ': _Compile error. User-defined type not defined_
- `Dim ust As UShort` ': _Compile error. User-defined type not defined_

**Comment by serkonda7** [comment]
Thanks for testing and clarification. 

You can make a PR with your list and implementing case insensitivity would be good too.

**Comment by bopoh13** [comment]
Thanks for fruitful exchange of views. I will prepare PR.

**Comment by bopoh13** [comment]
Note VBA7: [syntax backward compatibility with VBA6](https://docs.microsoft.com/en-us/office/vba/language/concepts/getting-started/64-bit-visual-basic-for-applications-overview)

**Comment by serkonda7** [comment]
> Note VBA7: [syntax backward compatibility with VBA6](https://docs.microsoft.com/en-us/office/vba/language/concepts/getting-started/64-bit-visual-basic-for-applications-overview)

It's be the best to use the keywords from the most recent vba version.
