### ISSUE TITLE
add icon

### ISSUE THREAD

**Issue by serkonda7** [serkonda7/vscode-vba#19]

**Comment by bopoh13** [comment]
I propose to add an icon https://icon-icons.com/icon/file-type-vba/130097
In the path `vscode-vba/images/logo.png`

**Comment by serkonda7** [comment]
@bopoh13 thanks for the proposal!
What do you think of adding an text like below?
![icon_256x256](https://user-images.githubusercontent.com/40118727/161116923-242d3117-3ec2-4f2c-85f1-db97c2cb713d.png)

**Comment by bopoh13** [comment]
@serkonda7 the text fits perfectly into the icon!

**Comment by h8nor** [comment]
Maybe you forgot to change the icon because
https://github.com/serkonda7/vscode-vba/blob/c5e2464b947e1656cc82b585f4921b5a36dd08e2/.vscodeignore#L11

**Comment by serkonda7** [comment]
> Maybe you forgot to change the icon because

That's not related. There simply was no icon.
