### ISSUE TITLE
AndAlso, OrElse, IsNot

### ISSUE THREAD

**Issue by stepanhakobyan** [serkonda7/vscode-vba#57]
I want to add highlighting for keywords `AndAlso`, `OrElse` and `IsNot`.
These keywords are not supported in VBA, but I want to use this extension for other VB language.
Is it OK?

**Comment by serkonda7** [comment]
I'm not sure this extension should be expanded to cover multiple VB dialects.
More advanced features are planned (and in early development stage) that are specific to VBA and Microsoft Office.

However I understand, that it may have benefits to not split development efforts.

I would like to have some research how easy/complicated it is, to have multiple language grammars based on a common base before giving making a decision.

Could you nonetheless please provide a link to some kind of docs or reference of the VB dialect.

**Comment by stepanhakobyan** [comment]
Here 
https://www.winwrap.com/web2/basic/#!/ref/WWB-doc_operators_oper.htm

**Comment by serkonda7** [comment]
My experiments with derived grammar files were not successful.
Personally I actually think that a fork of the extension (or you maintain some patches on top) is better than duplicating the whole grammar file.
I'm however open for further discussion.

**Comment by stepanhakobyan** [comment]
Thanks @serkonda7, I'll think about other ways to solve my problems. 
I believe we can close this issue.

**Comment by serkonda7** [comment]
@stepanhakobyan I took some more time to fiddle around and got a prototype working, that adds additional highlighting rules on top of the existing VBA grammar.
It's not really cleaned up but you can have a look here: https://github.com/serkonda7/vscode-vba/tree/vb-dialect-prototype

> To be clear: I do not know if this has limitations or shortcomings (especially with e.g. VBA keywords that should not be highlighted in the dialect)! 

If you like the approach in this prototype and build upon it, I would be open for including it in this extensions main tree.

**Comment by stepanhakobyan** [comment]
@serkonda7  I checked your prototype.
After fixing bug in package.json, the prototype worked and highlighted language as expected.
I tried to write a test for that, but didn't manage to. I'll need help with that.

I'll try to make a pull request for the dialect in a few days. 
Thanks.

**Comment by serkonda7** [comment]
Take the time you need for preparing a PR.
No worries regarding the test, I will help with that.

**Comment by serkonda7** [comment]
Btw you don't have to cover the complete syntax in a single PR. It's fine to span it over multiple ones, if that's easier for you.

**Comment by h8nor** [comment]
Are U trying PRs #58 #59 for the WWB dialect .NET?
> [In vain](10#issuecomment-1086848597).

**Comment by h8nor** [comment]
Some objects have a Note in [the documentation](57#issuecomment-1282752643)
> This language element is not VBA compatible.

**Comment by stepanhakobyan** [comment]
> Are U trying PRs #58 #59 for the WWB dialect .NET?
> 
> > [In vain](10#issuecomment-1086848597).

@h8nor No, This PR is for older WinWrap Basic for COM. 
The new WinWrap Basic for .NET is just Visual Basic.NET is works VS Code.

**Comment by h8nor** [comment]
You are mistaken at least on the link you provided.
![WWB-COM](https://user-images.githubusercontent.com/6163937/199281296-a72d83a9-0092-4999-ab23-f14964460ceb.png)

**Comment by stepanhakobyan** [comment]
@h8nor , WWB-COM is a superset of VBA. And that why #58 is another language dialect and not touching vba language syntax.

**Comment by serkonda7** [comment]
@h8nor as can be seen in the discussion above, we are fully aware of these incompatibilities.
Therefore we add the WWB syntax as a expansion of the VBA syntax.
The highlighting of code in VBA files should not be affected by anything defined in the WWB syntax file.

**Comment by h8nor** [comment]
Thank you for stand by the VBA standard.
Apparently I missed this discussion. I don't have time to test these changes yet.
Regards

**Comment by serkonda7** [comment]
@h8nor I verified them manually and also added a test to make sure VBA highlighting stays as is.
Should you still encounter any problems please report them, so we can fix it.
