### ISSUE TITLE
Dev Build of Extension works in VS-Code but does not show up in list of Extensions.

### ISSUE THREAD

**Issue by davidlbangs** [serkonda7/vscode-vba#73]
- VS Code Version: 1.7.7.3
- Extension (vscode-vba) Version: 0.8.1

**What did you do?**
I uninstalled the public version of VBA
I forked the repository and cloned it, then built it. 
I ran "run install-dev-ext" to create a development version. 
I installed it from the "out" folder as a VSIX

**Actual behaviour**

Result:  My VBA files are color coded again.  Before installing the VSIX they were not. 

However, no extension by the name of VBA is listed in VS Code Exensions. 

Without it being listed, I can't easily uninstall it.  Though when I deleted the folder under .vscode/extensions and restarted code, the code coloring had stopped. 

I considered the component needed a new name so that VSCode would not confuse it with the published package.
I changed packages.jon to list a different name and display name and build again.  Then installed the new VSIX. 

Code coloring started again.  Still nothing listed on the Exensions list in VSCode. 

**Expected behavior**

I have no idea whether this something wrong with the component, or whether something in vs code in my environment. 
I am entering this because it will hamper my ability to contribute because I will always think I broke the component somehow. 

Please let me know if you have any ideas about this.

**Comment by serkonda7** [comment]
Thanks for considering to contribute :smile: 

- Uninstalling the public version is not necessary as `install-dev-ext` uses the force flag.
- The extension should popup in the "Installed" section even before the reload
- You can find the current version there too.
- Following all steps from [Contributing.md](https://github.com/serkonda7/vscode-vba/blob/main/CONTRIBUTING.md#install-a-dev-version) should work.

On Linux you could also try `code --list-extensions --show-versions`.
If it is installed the output will include a line like `serkonda7.vscode-vba@0.8.1`

**Comment by davidlbangs** [comment]
Thank you.  I see that it is listed now.  Either it wasn't listed before, or I looked very badly.  

I will use the component. I looked at the yaml files and no suggestions at this time. If you don't mind, I plan to keep it forked so I can experiment with it, and will make a pull request if I make a good innovation.

I appreciate that you posted this.

**Comment by serkonda7** [comment]
No problem. Do all experiment as you like and feel free to reach create an issue or discussion if you have anything.
