### ISSUE TITLE
Making this repo the grammar used by GitHub for syntax highlighting 

### ISSUE THREAD

**Issue by DecimalTurn** [serkonda7/vscode-vba#76]
Currently, the grammar referenced by GiHub (via [Linguist](https://github.com/github-linguist/linguist)) for syntax highlighting of VBA code is the following repo :
https://github.com/peters-ben-0007/VBDotNetSyntax

Since it's a VB.NET repo, it works OK most of the times, but it would be better to replace it with a grammar that is specifically made for VBA's syntax like this repo.

I'm willing to make the PR to Linguist in order to make that change, but there might be changes needed to make this work, so I wanted to know if you approve of this idea.

**Comment by serkonda7** [comment]
Nice suggestion. I will look into it.

**Comment by serkonda7** [comment]
- https://github.com/github-linguist/linguist/pull/6436
- https://github.com/github-linguist/linguist/discussions/6437

**Comment by DecimalTurn** [comment]
Awesome! Let's wait to see what comes up in the discussion.

**Comment by serkonda7** [comment]
Well, the discussion is not really helpful and support for yaml is just awful:
https://github.com/github-linguist/linguist/issues/6438

I think it might be the best solution to create another repo, containing the JSON files.

**Comment by serkonda7** [comment]
@DecimalTurn I have created a repo with the JSON grammar: https://github.com/tiabeast/vscode-vba-json
But I closed my PR to the linguist repo. Please feel free to superseed it and just ping me if this approach does not work too.

**Comment by DecimalTurn** [comment]
Sure, I can make the PR, but I got the following error while running the `add-grammar` script:
```
3 errors found in new grammar 'repository `vendor/grammars/vscode-vba-json` (from https://github.com/tiabeast/vscode-vba-json.git)':
- Grammar conversion failed. File `syntaxes/language-configuration.json` failed to parse: Undeclared scope in grammar: `syntaxes/language-configuration.json` has no scope name
- Invalid regex in grammar: `source.vba` (in `syntaxes/vba.tmGrammar.json`) contains a malformed regex (regex "`(?i)(?<=\s+As\s+)([a-zA-Z]+)`": lookbehind assertion is not fixed length (at offset 16))
- Invalid regex in grammar: `source.vba` (in `syntaxes/vba.tmGrammar.json`) contains a malformed regex (regex "`(?i:\b(?<=(Call|Function|Sub)\s)`...": lookbehind assertion is not fixed length (at offset 31))
 ```

Regarding the first one, I think we can ignore it. It's just that Linguist won't include informations from `language-configuration.json`.

For the other 2 issues, looks like the regex engine that Linguist use is more picky when it comes to lookbehinds. However, it seems likes we could simply use non-capturing groups and it would keep the original outcome without the use of lookbehinds. I'll submit a PR for this.

**Comment by DecimalTurn** [comment]
Actually, for `language-configuration.json`, is it necessary in the repo? Could we just exclude it?

**Comment by serkonda7** [comment]
The language-configuration.json is not needed, I will remove it.

**Comment by serkonda7** [comment]
Thank you for bringing this up and your contributions!

**Comment by DecimalTurn** [comment]
My pleasure!
