### ISSUE TITLE
Support `Rem` comment delimiter

### ISSUE THREAD

**Issue by DecimalTurn** [serkonda7/vscode-vba#81]
### Description and Reproduction Steps

Type the following VBA code:

```vba
'Test comment
Rem Test comment

10 'Test comment
20 Rem Test comment

Labe1: 'Test comment
Labe2: Rem Test comment

```

### Current Behavior

Currently, the Rem comment delimiter is ignored:

![image](https://github.com/serkonda7/vscode-vba/assets/31558169/dfb20728-fd58-47d8-bd8b-e9b854aeb8ef)

### Expected Behavior

Comments using the `Rem` delimiter should work like comments using `'` when present at the start of a line. It should be ignored when `Rem` is not present at the start of a line.

From VBE :
![image](https://github.com/serkonda7/vscode-vba/assets/31558169/ff8dabf4-2fbc-447f-bc34-d9178a430fa3)

![image](https://github.com/serkonda7/vscode-vba/assets/31558169/6e54d94a-3741-479d-a6c6-81b5a8ab6fed)

### Additional Information

I know this feature is archaic, but it is supported in VBA for backward compatibility, so it would be good if this can be implemented here.

For reference, here is how it's currently implemented in other grammars:
* VBScript: https://github.com/SublimeText/VBScript/blob/79ca31f15449abfcf4eb61e9800ed19ecc9583b1/VBScript.tmLanguage#LL131
* VB.NET: https://github.com/peters-ben-0007/VBDotNetSyntax/blob/efaa4187fe75634c0f01c294c0d9624d141cd649/vbdotnet.tmLanguage#L157

### Environment details

OS: Windows 10
VS Code Version: 1.60.1
Extension Version: v0.8.0

**Comment by serkonda7** [comment]
Yes, this should be added to the grammar.

Reference: https://learn.microsoft.com/en-us/office/vba/language/reference/user-interface-help/rem-statement

Additional expected behavior from the docs:
```vba
MyStr1 = "Hello": Rem Comment after a statement separated by a colon.
```

Do you want to work on this?

**Comment by DecimalTurn** [comment]
Yeah, I can look into this. I've had a look at the [TextMate documentation](https://macromates.com/manual/en/language_grammars) and I think I understand better how to play with this now.

Also, I realize that while we are at it, we should also support multi-line comments that make use of the line continuation character (`_`) as well:

```vba
' Multi-line _ 
  comment
```

![image](https://github.com/serkonda7/vscode-vba/assets/31558169/6e2104fa-eada-45ff-8a21-109d4b07c030)

**Comment by serkonda7** [comment]
Thanks, if you have questions, feel free to ask and I will answer at my best.
