### ISSUE TITLE
FormattingCode_VBA

### ISSUE THREAD

**Issue by Rao0805** [serkonda7/vscode-vba#90]
### Describe the feature

Such as controlling indentation, setting line spacing, setting the case of tags and attribute names, etc., in order to maintain a concise and clear source code format and facilitate self maintenance when checking the program.
By utilizing the features of "formatting VBA code" and "purifying VBA code", it is possible to format and purify the VBA code of existing documents, achieving a unified VBA code format, deleting useless code, fixing code errors, optimizing code, and improving code quality.

### Additional Information

Format the code after saving
Right click to format the code

**Comment by serkonda7** [comment]
I agree, this would be a helpful feature.

**Comment by Rao0805** [comment]
Consider deleting empty lines

**Comment by Rao0805** [comment]
If you have time to reconsider deleting comments or customizing completion keywords
